// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sindika.AspNet.app015.Infrastructure.DataContext;

#nullable disable

namespace pringsewu.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251208092717_AddEventAndGalleryTable")]
    partial class AddEventAndGalleryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("event_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("event_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("event_isactive");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("event_isdefault");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("event_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Code", "IsDefault");

                    b.ToTable("dbs000_event");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("language_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("language_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("language_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("language_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("language_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("language_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("language_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("language_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("language_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Code");

                    b.ToTable("dbs000_language");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("menu_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("menu_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("menu_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("menu_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("menu_deleteddate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("menu_description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("menu_icon");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("menu_internalcode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("menu_isactive");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("boolean")
                        .HasColumnName("menu_isexpanded");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("menu_name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("menu_number");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("menu_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("menu_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "InternalCode", "Code", "Number", "IsExpanded");

                    b.ToTable("dbs000_menu");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.MenuPageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("menu_pageevent_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("menu_pageevent_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("menu_pageevent_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("menu_pageevent_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("menu_pageevent_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("menu_pageevent_isactive");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_pageevent_menuid");

                    b.Property<Guid>("PageEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_pageevent_pageeventid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("menu_pageevent_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("menu_pageevent_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("PageEventId");

                    b.HasIndex("IsActive", "MenuId", "PageEventId");

                    b.ToTable("dbs000_menu_pageevent");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("page_classname");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("page_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("page_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("page_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("page_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("page_deleteddate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("page_description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("page_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("page_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("page_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("page_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "ClassName", "Code");

                    b.ToTable("dbs000_page");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.PageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("page_event_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("page_event_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("page_event_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("page_event_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("page_event_deleteddate");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_event_eventid");

                    b.Property<bool>("HasEvent")
                        .HasColumnType("boolean")
                        .HasColumnName("page_event_hasevent");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("page_event_isactive");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_event_pageid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("page_event_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("page_event_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PageId");

                    b.HasIndex("IsActive", "EventId", "PageId", "HasEvent");

                    b.ToTable("dbs000_page_event");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("profile_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("profile_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_deleteddate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("profile_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("profile_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Code");

                    b.ToTable("dbs000_profile");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.ProfilePageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_page_event_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("profile_page_event_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_page_event_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("profile_page_event_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_page_event_deleteddate");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_page_event_eventid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("profile_page_event_isactive");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_page_event_pageid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_page_event_profileid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("profile_page_event_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_page_event_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PageId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("IsActive", "EventId", "PageId", "ProfileId");

                    b.ToTable("dbs000_profile_page_event");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("role_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("role_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("role_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("role_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("role_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("role_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("role_updateddate");

                    b.Property<Guid>("UserTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_usertypeid");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.HasIndex("IsActive", "Code", "UserTypeId");

                    b.ToTable("dbs000_role");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.RoleProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_profile_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("role_profile_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("role_profile_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("role_profile_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("role_profile_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("role_profile_isactive");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_profile_profileid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_profile_roleid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("role_profile_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("role_profile_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("RoleId");

                    b.HasIndex("IsActive", "ProfileId", "RoleId");

                    b.ToTable("dbs000_role_profile");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("user_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("user_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_deleteddate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("user_hash");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("user_image");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("user_isactive");

                    b.Property<bool>("IsRemember")
                        .HasColumnType("boolean")
                        .HasColumnName("user_isremember");

                    b.Property<bool>("IsSuper")
                        .HasColumnType("boolean")
                        .HasColumnName("user_issuper");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("user_isverified");

                    b.Property<Guid?>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_languageid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("user_password");

                    b.Property<string>("Salt")
                        .HasColumnType("text")
                        .HasColumnName("user_salt");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("user_token");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("user_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_updateddate");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("user_username");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_zoneid");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ZoneId");

                    b.HasIndex("IsActive", "Token", "LanguageId", "ZoneId");

                    b.ToTable("dbs000_user");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usertype_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usertype_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("usertype_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usertype_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("usertype_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usertype_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("usertype_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usertype_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("usertype_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usertype_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Code");

                    b.ToTable("dbs000_usertype");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.UserUserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_usertype_role_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("user_usertype_role_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_usertype_role_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("user_usertype_role_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_usertype_role_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("user_usertype_role_isactive");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("user_usertype_role_isenabled");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_usertype_role_roleid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("user_usertype_role_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_usertype_role_updateddate");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_usertype_role_userid");

                    b.Property<Guid>("UserTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_usertype_role_usertypeid");

                    b.Property<string>("user_usertype_role_discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "UserId", "UserTypeId", "RoleId");

                    b.ToTable("dbs000_user_usertype_role");

                    b.HasDiscriminator<string>("user_usertype_role_discriminator").HasValue("UserUserType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("zone_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("zone_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("zone_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("zone_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("zone_isactive");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("zone_label");

                    b.Property<string>("Offset")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("zone_offset");

                    b.Property<int?>("OffsetMinute")
                        .HasColumnType("integer")
                        .HasColumnName("zone_offsetminute");

                    b.Property<string>("TZCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("zone_tzcode");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("zone_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("zone_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("dbs000_zone");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<Guid>("CityTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_citytypeid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("city_code");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_countryid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("city_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("city_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("city_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("city_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("city_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("city_name");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_provinceid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("city_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("city_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("CityTypeId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("dbs015_city");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.CityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("citytype_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("citytype_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("citytype_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("citytype_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("citytype_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("citytype_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("citytype_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("citytype_name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("citytype_shortname");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("citytype_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("citytype_updateddate");

                    b.HasKey("Id");

                    b.ToTable("dbs015_citytype");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("country_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("country_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("country_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("country_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("country_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("country_name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("country_shortname");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("country_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("country_updateddate");

                    b.HasKey("Id");

                    b.ToTable("dbs015_country");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("developer_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("developer_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("developer_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("developer_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("developer_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("developer_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("developer_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("developer_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("developer_phone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("developer_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("developer_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Code");

                    b.ToTable("dbs000_developer");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_cityid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("district_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("district_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("district_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("district_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("district_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("district_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("district_name");

                    b.Property<string>("PCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district_pcode");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_provinceid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("district_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("district_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("dbs015_district");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.DonationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("donation_event_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("donation_event_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("donation_event_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donation_event_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("donation_event_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donation_event_deleteddate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("donation_event_description");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donation_event_enddate");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("donation_event_imgurl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("donation_event_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("donation_event_name");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donation_event_startdate");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("donation_event_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donation_event_updateddate");

                    b.HasKey("Id");

                    b.ToTable("dbs015_donation_event");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.DonationGallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("donation_gallery_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("donation_gallery_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donation_gallery_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("donation_gallery_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donation_gallery_deleteddate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("donation_gallery_description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("donation_gallery_eventid");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("donation_gallery_imgurl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("donation_gallery_isactive");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("donation_gallery_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("donation_gallery_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("dbs015_donation_gallery");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("employee_address");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("employee_birthdate");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("employee_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("employee_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("employee_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("employee_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("employee_deleteddate");

                    b.Property<string>("GenderCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("employee_gendercode");

                    b.Property<DateOnly>("HiredDate")
                        .HasColumnType("date")
                        .HasColumnName("employee_hireddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("employee_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("employee_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_phone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("employee_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("employee_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Code");

                    b.ToTable("dbs015_employee");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("gender_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("gender_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gender_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("gender_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gender_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("gender_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("gender_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("gender_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gender_updateddate");

                    b.HasKey("Id");

                    b.ToTable("dbs015_gender");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("province_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("province_code");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("province_countryid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("province_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("province_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("province_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("province_deleteddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("province_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("province_name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("province_shortname");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("province_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("province_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("dbs015_province");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.SubDistrict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("subdistrict_id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("subdistrict_cityid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subdistrict_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("subdistrict_createdby");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subdistrict_createddate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("subdistrict_deletedby");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subdistrict_deleteddate");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("subdistrict_districtid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("subdistrict_isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("subdistrict_name");

                    b.Property<string>("PCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subdistrict_pcode");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("subdistrict_provinceid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("subdistrict_updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subdistrict_updateddate");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("dbs015_subdistrict");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.DeveloperUserType", b =>
                {
                    b.HasBaseType("Sindika.AspNet.Common.Entities.UserUserType");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_usertype_role_developerid");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("dbs000_user_usertype_role", (string)null);

                    b.HasDiscriminator().HasValue("DeveloperUserType");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.EmployeeUserType", b =>
                {
                    b.HasBaseType("Sindika.AspNet.Common.Entities.UserUserType");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_usertype_role_employeeid");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("dbs000_user_usertype_role", (string)null);

                    b.HasDiscriminator().HasValue("EmployeeUserType");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.MenuPageEvent", b =>
                {
                    b.HasOne("Sindika.AspNet.Common.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sindika.AspNet.Common.Entities.PageEvent", "PageEvent")
                        .WithMany()
                        .HasForeignKey("PageEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("PageEvent");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.PageEvent", b =>
                {
                    b.HasOne("Sindika.AspNet.Common.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sindika.AspNet.Common.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.ProfilePageEvent", b =>
                {
                    b.HasOne("Sindika.AspNet.Common.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sindika.AspNet.Common.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sindika.AspNet.Common.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Page");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.Role", b =>
                {
                    b.HasOne("Sindika.AspNet.Common.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.RoleProfile", b =>
                {
                    b.HasOne("Sindika.AspNet.Common.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sindika.AspNet.Common.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sindika.AspNet.Common.Entities.User", b =>
                {
                    b.HasOne("Sindika.AspNet.Common.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.HasOne("Sindika.AspNet.Common.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("Language");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.City", b =>
                {
                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.CityType", "CityType")
                        .WithMany()
                        .HasForeignKey("CityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityType");

                    b.Navigation("Country");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.District", b =>
                {
                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.DonationGallery", b =>
                {
                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.DonationEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.Province", b =>
                {
                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.SubDistrict", b =>
                {
                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.DeveloperUserType", b =>
                {
                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId");

                    b.HasOne("Sindika.AspNet.Common.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("Sindika.AspNet.Common.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("Sindika.AspNet.Common.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Sindika.AspNet.app015.Domain.Entities.EmployeeUserType", b =>
                {
                    b.HasOne("Sindika.AspNet.app015.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Sindika.AspNet.Common.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("Sindika.AspNet.Common.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("Sindika.AspNet.Common.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("UserType");
                });
#pragma warning restore 612, 618
        }
    }
}
